FROM node:17-alpine3.14 as builder
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install application dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install -g ionic
RUN npm install
# add app
COPY . ./
RUN npm run build 

FROM nginx:alpine 

COPY --from=builder /app/build /usr/share/nginx/html